name: Release

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build from (e.g., v1.2.3)"
        required: true
        default: ""

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        otp: ["27.3.4"]
        elixir: ["1.18.4"]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout specified tag (manual dispatch only)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' }}
        run: |
          git fetch --tags
          git checkout ${{ inputs.tag }}

      - name: Set up Elixir
        uses: marmelasoft/elixir-setup@main
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Compile project
        run: mix compile --all-warnings --warnings-as-errors

      - name: Build docs
        run: mix docs

      - name: Build archive
        run: mix archive.build

      - name: Get archive filename
        id: archive_name
        run: |
          echo "ARCHIVE_FILE=$(ls *.ez | head -n 1)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: ${{ env.ARCHIVE_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix deps.get
          mix hex.publish --yes
